title: Matias Afur
logo: /assets/img/avatar.png
description: I am a dedicated developer specializing in front-end and mobile app development with React Native and React.js. I also have strong back-end skills using Node.js and Express.js. My background in electronic engineering and IoT enhances my ability to deliver comprehensive and innovative solutions.
theme: jekyll-theme-minimal
